name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev


permissions:
  id-token: write
  contents: read

jobs:
  build-agent:
    name: Build agent
    uses: ./.github/workflows/build_agent.yaml
    secrets: inherit

  deploy-infa:
    name: Deploy infra
    uses: ./.github/workflows/deploy.yaml
    needs: [ build-agent]
    with:
      environment: ${{ github.ref_name == 'main' && 'staging' || 'dev' }}
    secrets: inherit
