name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

env:
  AWS_S3_TOFU_BUCKET_NAME: ${{ vars.AWS_S3_TOFU_BUCKET_NAME }}
  AWS_DEPLOYMENT_ACCOUNT_ID: ${{ vars.AWS_DEPLOYMENT_ACCOUNT_ID }}
  AWS_DEPLOYMENT_REGION_NAME: ${{ vars.AWS_DEPLOYMENT_REGION_NAME }}
  AWS_DEPLOYMENT_ROLE_ARN: ${{ vars.AWS_DEPLOYMENT_ROLE_ARN }}
  TF_VAR_env: ${{ inputs.environment }}
  TF_VAR_region: ${{ vars.AWS_DEPLOYMENT_REGION_NAME }}
#  TF_VAR_ilert_webhook_url: ${{ secrets.ILERT_WEBHOOK_URL }}


concurrency: ${{ inputs.environment }}

jobs:
  apply-tofu-and-run-migration:
#    runs-on: self-hosted
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment }}

    steps:
      - uses: opentofu/setup-opentofu@v1

      - name: Git clone the repository
        uses: actions/checkout@v4
#        with:`
#          lfs: true
#
#      - name: Checkout LFS objects
#        run: git lfs checkout

      - name: Set version hash
        id: version
        run: |
          echo "HASH_AGENT=$(find agent -type f -print0 | sort -z | xargs -0 sha1sum | sha1sum | rev | cut -c4- | rev)" >> $GITHUB_OUTPUT

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_DEPLOYMENT_ROLE_ARN }}
          role-session-name: OpensearchAgentDeploymentSession
          aws-region: ${{ env.AWS_DEPLOYMENT_REGION_NAME }}

      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Tofu init
        run: tofu init -backend-config="bucket=${{ env.AWS_S3_TOFU_BUCKET_NAME }}" -backend-config="region=${{ env.AWS_DEPLOYMENT_REGION_NAME }}"
        working-directory: ./infra/

      - name: Tofu plan
        run: tofu plan -var agent_image_version="${{ steps.version.outputs.HASH_AGENT }}"
        working-directory: ./infra/

      - name: Tofu apply
        run: tofu apply --auto-approve -var agent_image_version="${{ steps.version.outputs.HASH_AGENT }}"
        working-directory: ./infra/

#      - name: Set up python
#        id: setup-python
#        uses: actions/setup-python@v4
#        with:
#          python-version: '3.9.13'
#
#      - name: Install poetry
#        run: |
#          pip install -U poetry
#        shell: bash
#        working-directory: ./migrations/athena/
#
#      - name: Setup a local virtual environment
#        run: |
#          poetry config virtualenvs.create true --local
#          poetry config virtualenvs.in-project true --local
#        working-directory: ./migrations/athena/
#
#      - name: Configure cache for python packages
#        uses: actions/cache@v3
#        with:
#          path: migrations/athena/.venv
#          key: ${{ runner.os }}-build-deploy-migration-${{ env.BRANCH_NAME }}-${{ hashFiles('migrations/athena/poetry.lock') }}
#          restore-keys: |
#            ${{ runner.os }}-build-deploy-migration-${{ env.BRANCH_NAME }}-
#
#      - name: Install the project dependencies
#        run: poetry install --without test
#        working-directory: ./migrations/athena/
#
#      - name: Run migrations on opensearch
#        if: ${{ inputs.environment == 'prod' }}
#        run: |
#          tofu init -backend-config="bucket=${{ vars.AWS_S3_TOFU_BUCKET_NAME }}" -backend-config="region=${{ vars.AWS_REGION_NAME }}"
#          tofu plan
#          tofu apply --auto-approve
#        working-directory: ./migrations/opensearch
#
#      - name: Run migrations on athena
#        if: ${{ inputs.environment == 'prod' }}
#        run: |
#          poetry run python main.py --regionName ${{ vars.AWS_REGION_NAME }} --accountId ${{ vars.AWS_ACCOUNT_ID }} --envName ${{ inputs.environment }}
#        working-directory: ./migrations/athena/src

#  trigger-sejmoskop-web-build:
#    runs-on: ubuntu-latest
#    needs: [ apply-tofu-and-run-migrations ]
#
#    steps:
#      - name: Trigger sejmoskop-web build
#        uses: convictional/trigger-workflow-and-wait@v1.6.1
#        with:
#          owner: torm89
#          repo: sejmoskop-web
#          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
#          github_user: torm89
#          workflow_file_name: pipeline.yaml
#          ref: ${{ (github.head_ref || github.ref_name) == 'main' && 'main' || 'dev' }}
#          propagate_failure: true
#          trigger_workflow: true
#          wait_workflow: true
