name: Deploy

on:
  release:
    types: [published]


permissions:
  id-token: write
  contents: read

jobs:
  deploy-tofu:
    name: Deploy tofu
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: prod
    secrets: inherit
